apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: address-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
      - name: address-service
        image: satheeshch/address-service:latest
        ports:
        - containerPort: 80
